version: '3'
services:
  node_app:
    image: node
    ports:
      - "4000:4000"
    networks:
      - container-network

networks:
  container-network:
    external: true
    driver: bridge